"""Make timetable class_id non-null

Revision ID: 5dcff5ad9e62
Revises: 9366027274aa
Create Date: 2026-10-01 14:29:29.893023

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5dcff5ad9e62"
down_revision: str | Sequence[str] | None = "9366027274aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("timetable", "class_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("timetable", "class_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
